### ISSUE TITLE
CC eats all custom payload packets for other mods that inject after CC

### ISSUE THREAD

**Issue by maruohon** [Ivan-1F/carpetclient#1]
The handler method here: https://github.com/Ivan-1F/carpetclient/blob/a62b0e050d81b802e54f5007c4d0654c2d659056/src/main/java/me/ivan1f/carpetclient/network/NetworkHandler.java#L22-L33 causes all custom payload packet handling to get cancelled, except unknown CC packets. Meaning any other mods injecting after the CC packet handler will not receive their packets.

**Comment by Ivan-1F** [comment]
Fixed in v1.1.1: https://github.com/Ivan-1F/carpetclient/releases/tag/v1.1.1

Thanks for your report
